### ISSUE TITLE
feat: add more programming languages code examples

### ISSUE THREAD

**Issue by d1y** [braver/programmingfonts#110] opened 2022-04-15 04:36 UTC
After switching programming languages, you can switch example code in real time

Can you try the sample code using moncao-editor :)

https://github.com/microsoft/monaco-editor/tree/gh-pages

**Comment by qqii** [comment] 2023-01-08 02:57
Duplicate of #104. 

Also, what's up with the default JavaScript example? 

>```javascript
> console.log "oO08 iIlL1 g9qCGQ ~-+=>";
>```
> (https://github.com/braver/programmingfonts/blob/gh-pages/index.html#L300)

**Comment by braver** [comment] 2023-01-08 09:21
> what's up with the default JavaScript example?

The sample code isn’t just any random piece of JavaScript. It has words and sequences of characters chosen to highlight aspects of fonts that are especially relevant in code and to help you evaluate the fonts. It has contains the entire alphabet, and sequences that help you see if a font allows for easy distinction between (for instance) o and zero, and if arrows and operators line up nicely.

That‘s also why it isn’t trivial to add a menu with dozens of code samples.

That said, this issue is indeed duplicate.

**Closed as completed by braver** 2023-01-08 09:21 UTC
Labels: enhancement

**Comment by qqii** [comment] 2023-01-09 09:42
I was commenting about the fact that `console.log` doesn't have `(` and `)` making it a syntax error.
